config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "posts#index"

  resources :posts, except: %i[new]
  resources :comments
  resources :notifications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :mentions, as: :record, dependent: :destroy, class_name: "Noticed::Event"

  validates :body, presence: :true

  after_create_commit { broadcast_notifications }

  private

  def broadcast_notifications
    message = "#{user.email} commented on your post: #{post.title}"
    
    CommentNotifier.with(record: self, message: ).deliver_later(post.user)
    
    broadcast_prepend_to "notifications_#{post.user.id}",
                          target: "notifications_#{post.user.id}",
                          partial: "notifications/notification",
                          locals: { user:, post:, message:}
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :mentions, as: :record, dependent: :destroy, class_name: "Noticed::Event"

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy, class_name: "Noticed::Notification"
  has_many :mentions, as: :record, dependent: :destroy, class_name: "Noticed::Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)

        respond_to do |format|
            if @comment.save
                flash[:notice] = "New Comment created"
                format.turbo_stream
            else
                flash[:alert] = @comment.errors.full_messages.first.to_s
                format.turbo_stream
            end
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    def index
        @notifications = current_user.notifications.includes(:event).reverse
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        flash[:notice] = "Post successfully created"
        format.turbo_stream
      else
        flash[:alert] = @post.errors.full_messages.first.to_s
        format.turbo_stream
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
    <div class='flex flex-col gap-2'>
        <p><%= comment.body %></p>
        <p class='text-xs text-gray-400'><%= comment.user.email %></p>
    </div>
<% end %>

app/views/comments/_comments.html.erb
<%= turbo_frame_tag "comments_#{dom_id(post)}" do %>
    <div class='flex flex-col gap-2'>
        <% comments.each do |comment | %>
            <%= turbo_frame_tag dom_id(comment) do %>
                <%= render partial: 'comments/comment', locals: { comment: comment } %>
            <% end %>
        <% end %>
    </div>
<% end %>

app/views/comments/_form.html.erb
<%= turbo_frame_tag 'comment_form' do %>
  <%= form_with model: comment do |form| %>
    <div>
      <%= form.label :body %>
      <%= form.text_area :body %>
    </div>

    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :post_id, value: post.id %>

    <div>
      <%= form.submit "Comment" %>
    </div>
  <% end %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update 'toast', partial: 'layouts/toast' %>
<%= turbo_stream.replace 'comment_form', partial: 'comments/form', locals: { comment: Comment.new, post: @comment.post } %>
<%= turbo_stream.append "comments_#{dom_id(@comment.post)}", partial: 'comment', locals: { comment: @comment, post: @comment.post } %>

app/views/layouts/_header.html.erb
<header class='flex flex-row justify-between p-6 md:p-12 bg-gray-100'>
    <nav>
        <ul class='flex flex-row gap-4'>
            <li>
                <%= link_to "Home", root_path %>
            </li>
            <li>
                <%= link_to "Notifications", notifications_path %>
            </li>
        </ul>
    </nav>
    <div class='flex gap-4'>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
        </svg>
        <% if user_signed_in? %>
            <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete } %>
        <% else %>
            <%= link_to "Log In", new_user_session_path %>
        <% end %>
    </div>
</header>

app/views/layouts/_toast.html.erb
<%= turbo_frame_tag "toast" do %>
    <% if notice %>
        <div class='bg-green-100 p-2 m-2 rounded-md'><%= notice %></div>
    <% elsif alert %>
        <div class='bg-red-100 p-2 m-2 rounded-md'><%= alert %></div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full w-full">
  <head>
    <title>NotificationsPlayground</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="h-full w-full min-h-screen max-w-screen overflow-x-hidden">
    <%= render partial: 'layouts/toast' %>
    <%= render partial: 'layouts/header' %>
    
    <div class='h-full w-full container mx-auto p-6 md:p-12'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notifications/_notification.html.erb
<div class='flex flex-col'>
    <%= message %>
</div>

app/views/notifications/index.html.erb
<% if @notifications.empty? %>
    <p>No notifications to display</p>
<% else %>
    <%= turbo_stream_from "notifications_#{current_user.id}" %>
    <%= turbo_frame_tag "notifications_#{current_user.id}" do %>
        <ul>
            <% @notifications.each do |notification| %>
                <li>
                    <div class='flex flex-col'>
                        <%= notification.message %>
                    </div>
                </li>
            <% end %>
        </ul>
    <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= turbo_frame_tag 'post_form' do %>
  <%= form_with model: post do |form| %>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.text_area :body %>
    </div>

    <%= form.hidden_field :post_id, value: params[:id] %>
    <%= form.hidden_field :user_id, value: current_user.id %>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class='h-fit w-full p-4 rounded-md bg-gray-100'>
  <%= link_to post do %>
    <div class='flex flex-row items-end gap-2'>
      <h3 class='text-3xl'>
        <%= post.title %>
      </h3>
      <p class='text-xs text-gray-400'>
        <%= post.user.email %>
      </p>
    </div>

    <p class='my-4'>
      <%= post.body %>
    </p>
  <% end %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.update 'toast', partial: 'layouts/toast' %>
<%= turbo_stream.replace 'post_form', partial: 'form', locals: { post: Post.new } %>
<%= turbo_stream.append 'posts', partial: 'post', locals: { post: @post } %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class='h-full w-full flex flex-col gap-4'>
  <% if user_signed_in? %>
    <%= turbo_frame_tag 'post_form' do %>
      <%= render partial: 'form', locals: { post: @post } %>
    <% end %>
  <% end %>

  <div id="posts" class='flex flex-col gap-2'>
    <% @posts.each do |post| %>
      <%= render post %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<div class='flex flex-col gap-4'>
  <%= link_to "Back to posts", posts_path, class: 'underline' %>

  <%= render @post %>

  <div class='flex flex-row md:flex-col gap-2'>
    <%= button_to "Edit", edit_post_path(@post), class: 'min-w-24 border border-gray-200 bg-transparent hover:bg-gray-100' %>
    <%= button_to "Delete", @post, method: :delete, class: 'min-w-24 border border-red-400 bg-transparent hover:bg-red-100' %>
  </div>

  <%= turbo_frame_tag 'comment_form' do %>
    <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
  <% end %>

  <div class='flex flex-col gap-2'>
    <h2 class='text-lg font-bold'>Comments</h2>
    <%# turbo_stream_from "comments_#{dom_id(@post)}" %>
    <%= turbo_frame_tag "comments_#{dom_id(@post)}" do %>
      <% render partial: 'comments/comments', locals: { comments: @comments, post: @post } %>
    <% end %>
  </div>
</div>